# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Axis_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(max_length=200)),
                ('y', models.IntegerField(default=0)),
                ('data_set_code', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Axis_Labels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_units', models.CharField(max_length=200)),
                ('y_units', models.CharField(max_length=200)),
                ('data_set_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.Axis_Data')),
            ],
        ),
    ]
