# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axis_data',
            name='data_set_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.Axis_Labels'),
        ),
        migrations.AlterField(
            model_name='axis_labels',
            name='data_set_code',
            field=models.IntegerField(default=0),
        ),
    ]
